package org.myeslib.jdbi.function;

import com.google.common.eventbus.EventBus;
import org.myeslib.core.AggregateRoot;
import org.myeslib.core.Command;
import org.myeslib.core.Event;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static com.google.common.base.Preconditions.checkNotNull;

public class StatefulEventBus {

    private static final Logger logger = LoggerFactory.getLogger(StatefulEventBus.class);
    private final AggregateRoot aggregateRoot;
    private final EventBus bus;
    private final List<Event> events;
    private final List<Command> commands;

    public StatefulEventBus(AggregateRoot aggregateRoot, EventBus bus, List<Event> events, List<Command> commands) {
        checkNotNull(bus);
        this.bus = bus;
        checkNotNull(events);
        this.events = events;
        checkNotNull(commands);
        this.commands = commands;
        checkNotNull(aggregateRoot);
        this.aggregateRoot = aggregateRoot;
        bus.register(aggregateRoot);
    }

    public StatefulEventBus(AggregateRoot aggregateRoot, EventBus bus) {
        checkNotNull(bus);
        this.bus = bus;
        this.events = new ArrayList<>();
        this.commands = new ArrayList<>();
        checkNotNull(aggregateRoot);
        this.aggregateRoot = aggregateRoot;
        bus.register(aggregateRoot);
    }

    public StatefulEventBus(AggregateRoot aggregateRoot) {
        this.bus = new EventBus();
        this.events = new ArrayList<>();
        this.commands = new ArrayList<>();
        checkNotNull(aggregateRoot);
        this.aggregateRoot = aggregateRoot;
        bus.register(aggregateRoot);
    }

    public void apply(Event event) {
        checkNotNull(event);
        logger.info("applying event {} generated by an operation on {}", event, aggregateRoot);
        bus.post(event);
        logger.info("status after event applied {}", aggregateRoot);
        events.add(event);
    }

    public void emit(Command command) {
        checkNotNull(command);
        commands.add(command);
        logger.info("emitted command {} generated by an operation on {}", command, aggregateRoot);
    }

    public List<Event> getEvents() {
        bus.unregister(aggregateRoot);
        return Collections.unmodifiableList(events);
    }

    public List<Command> getCommands() {
        return Collections.unmodifiableList(commands);
    }

}
