package org.myeslib.jdbi.infra;

import com.google.common.eventbus.EventBus;
import org.myeslib.core.AggregateRoot;
import org.myeslib.core.Event;
import org.myeslib.infra.InteractionContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static com.google.common.base.Preconditions.checkNotNull;

@Deprecated
public class EventBusInteractionContext implements InteractionContext {

    private static final Logger logger = LoggerFactory.getLogger(EventBusInteractionContext.class);
    private final AggregateRoot aggregateRoot;
    private final EventBus bus;
    private final List<Event> events;

    public EventBusInteractionContext(AggregateRoot aggregateRoot) {
        this.bus = new EventBus();
        this.events = new ArrayList<>();
        checkNotNull(aggregateRoot);
        this.aggregateRoot = aggregateRoot;
        bus.register(aggregateRoot);
    }

    @Override
    public void apply(Event event) {
        checkNotNull(event);
        logger.debug("applying event {} generated by an operation on {}", event, aggregateRoot);
        bus.post(event);
        logger.debug("status after event applied {}", aggregateRoot);
        events.add(event);
    }

    @Override
    public List<Event> getAppliedEvents() {
        bus.unregister(aggregateRoot);
        return Collections.unmodifiableList(events);
    }

}
