package org.myeslib.stack1;

import com.google.common.eventbus.EventBus;
import org.myeslib.core.EventSourced;
import org.myeslib.data.Event;
import org.myeslib.infra.InteractionContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static com.google.common.base.Preconditions.checkNotNull;

@Deprecated
public class EventBusInteractionContext implements InteractionContext {

    private static final Logger logger = LoggerFactory.getLogger(EventBusInteractionContext.class);
    private final EventSourced eventSourced;
    private final EventBus bus;
    private final List<Event> events;

    public EventBusInteractionContext(EventSourced eventSourced) {
        this.bus = new EventBus();
        this.events = new ArrayList<>();
        checkNotNull(eventSourced);
        this.eventSourced = eventSourced;
        bus.register(eventSourced);
    }

    @Override
    public void emit(Event event) {
        checkNotNull(event);
        logger.debug("applying event {} generated by an operation on {}", event, eventSourced);
        bus.post(event);
        logger.debug("status after event applied {}", eventSourced);
        events.add(event);
    }

    @Override
    public List<Event> getEmittedEvents() {
        bus.unregister(eventSourced);
        return Collections.unmodifiableList(events);
    }

}
