package org.myeslib.stack1.infra;

import org.myeslib.core.AggregateRoot;
import org.myeslib.data.Command;
import org.myeslib.data.Event;
import org.myeslib.infra.SagaInteractionContext;
import org.myeslib.stack1.infra.helpers.MultiMethod;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static com.google.common.base.Preconditions.checkNotNull;

public class Stack1SagaInteractionContext implements SagaInteractionContext {

    private static final Logger logger = LoggerFactory.getLogger(Stack1SagaInteractionContext.class);
    private final AggregateRoot aggregateRoot;
    private final MultiMethod mm ;
    private final List<Event> events;
    private final List<Command> commands;

    public Stack1SagaInteractionContext(AggregateRoot aggregateRoot) {
        checkNotNull(aggregateRoot);
        this.aggregateRoot = aggregateRoot;
        this.mm = MultiMethod.getMultiMethod(aggregateRoot.getClass(), "on");
        this.events = new ArrayList<>();
        this.commands = new ArrayList<>();
    }

    @Override
    public void emit(Event event) {
        checkNotNull(event);
        logger.debug("applying event {} generated by an operation on {}", event, aggregateRoot);
        _applyEventsOn(aggregateRoot, event);
        logger.debug("status after event applied {}", aggregateRoot);
        events.add(event);
    }

    @Override
    public List<Event> getEmittedEvents() {
        return Collections.unmodifiableList(events);
    }

    private void _applyEventsOn(AggregateRoot instance, Event event) {
        try {
            mm.invoke(instance, event);
        } catch (Exception e) {
            throw new RuntimeException("Error when applying events via reflection", e.getCause());
        }
    }

    @Override
    public void emit(Command command) {
        commands.add(command);
    }

    @Override
    public List<Command> getEmittedCommands() {
        return commands;
    }
}
