package org.myeslib.stack1.infra;

import org.myeslib.core.EventSourced;
import org.myeslib.data.Command;
import org.myeslib.data.Event;
import org.myeslib.infra.SagaInteractionContext;
import org.myeslib.stack1.infra.helpers.MultiMethod;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static com.google.common.base.Preconditions.checkNotNull;

public class Stack1SagaInteractionContext implements SagaInteractionContext {

    private static final Logger logger = LoggerFactory.getLogger(Stack1SagaInteractionContext.class);
    private final EventSourced eventSourced;
    private final MultiMethod mm ;
    private final List<Event> events;
    private final List<Command> commands;

    public Stack1SagaInteractionContext(EventSourced eventSourced) {
        checkNotNull(eventSourced);
        this.eventSourced = eventSourced;
        this.mm = MultiMethod.getMultiMethod(eventSourced.getClass(), "on");
        this.events = new ArrayList<>();
        this.commands = new ArrayList<>();
    }

    @Override
    public void emit(Event event) {
        checkNotNull(event);
        logger.info("applying event {} generated by an operation on {}", event, eventSourced);
        _applyEventsOn(eventSourced, event);
        logger.debug("status after event applied {}", eventSourced);
        events.add(event);
    }

    @Override
    public List<Event> getEmittedEvents() {
        return Collections.unmodifiableList(events);
    }

    private void _applyEventsOn(EventSourced instance, Event event) {
        try {
            mm.invoke(instance, event);
        } catch (Exception e) {
            throw new RuntimeException("Error when applying events via reflection", e.getCause());
        }
    }

    @Override
    public void emit(Command command) {
        commands.add(command);
    }

    @Override
    public List<Command> getEmittedCommands() {
        return commands;
    }
}
